# Generated by Django 2.2 on 2023-01-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
